### ISSUE TITLE
Some wallets are failing on Holder attempts to prove with a revoked credential with a prover that doesn't care if it was revoked

### ISSUE THREAD

**Issue by nodlesh** [ianco/aries-agent-test-harness#392] opened 2021-11-24 15:09 UTC
0441 Revocation best practices states, "The absence of any non-revocation interval applicable to a requested item signifies that the verifier has no interest in its credential's non-revocation status."
So the test isn't sending a non-revocation interval with the proof request, therefore the verifier doesn't care about the revocation status, thus the proof should verify with the revoked cred.
https://github.com/sklump/aries-rfcs/tree/master/concepts/0441-present-proof-best-practices

Some wallets are failing on this test. It needs to be investigated where this issue resides. The running theory; What is causing Acapy to not verify the proof is it may very well be that the holder/wallet is sending a proof of non-revocation even when the proof request didn't ask for a non-revocation interval, and Acapy doesn't like that and is failing the verification. Acapy shouldn't care at this point if non-revocation is included in the proof IMO.

**Comment by swcurran** [comment] 2021-11-24 15:27
This is about one of @esune 's favourite rants!!!  Fun stuff.

@esune -- if you have any guidance on what is happening, please let @ianco know.  @ianco , can you please test this?

Scenario is that the Proof Request does not include anything about revocation, the holder has a credential to satisfy the PR that is revokable.  What happens?  I think the correct answer is that whether or not the holder sends a Proof-of-non-revocation, if the proof is valid, the verifier should accept it.  What I don't know is what Indy is doing under the covers in this scenario.  

- Is ACA-Py doing anything as the holder to trigger generation (or not) of the proof-of-non-revocation?
- What about other holders? 
- What about on verification -- is ACA-Py doing anything to the proof?

Note that this scenario can happen because the verifier doesn't know if the holder has a credential that is revokable or not. For example, there are 2 issuers of a credential type, and one has made theirs revokable and the other hasn't, and the verifier will accept a credential from either issuer.

For the initial evaluation, please use a "not revoked" credential and make sure that works -- that the result is "verified = true".  Then we can get into the scenario of the credential being revoked -- which adds to the fun.

**Comment by ianco** [comment] 2021-11-24 16:53
Aca-py will remove revocation information from the provided proof if the credential is non-revocable.  (Fixed recently here:  https://github.com/hyperledger/aries-cloudagent-python/pull/1465)

I suppose we need similar logic if a non-revocation proof was provided but not requested.

I believe Indy-sdk anoncreds will fail verification if the provided proof doesn't match what was requested (revocation-wise).

**Comment by ianco** [comment] 2021-11-24 16:57
@nodlesh which tests/wallets are failing this test?

**Comment by nodlesh** [comment] 2021-11-24 17:17
The test is T001-HIPE0011
We have seen it in the NorthernBlock Orbit wallet, and potentially in the DIT wallet that SuneetBendre is using. We have a thread with them in the AATH RocketChat channel.   Both of these wallets are not publicly available.

**Comment by nodlesh** [comment] 2021-11-24 17:19
@ianco This case in particular has a revocable credential that has been revoked, but the verifier doesn't(shouldn't) care of its revocation status.

**Comment by ianco** [comment] 2021-11-24 17:53
I wonder if the PR I linked above has contributed to this problem.  previously aca-py was over-aggressively removing the timestamps on provided proofs (allowing holder/provers to "fake" proofs ...  somehow ... ), the update removes timestamps based on the revocability of the credentials (based on cred def) so maybe now is too conservative ...

I'll see if I can duplicate using aca-py

**Comment by swcurran** [comment] 2021-11-24 17:56
I think that's the best approach -- document what ACA-Py is doing (and adjust if it is doing something wrong) -- and then make sure that it makes sense.  Perhaps a table to conditions and expected behaviour is needed.

**Comment by esune** [comment] 2021-11-24 18:52
> This is about one of @esune 's favourite rants!!! Fun stuff.
> 
> @esune -- if you have any guidance on what is happening, please let @ianco know. @ianco , can you please test this?
> 
I think Ian has it covered as he has worked on this specific realm fairly recently, I'll try and keep an eye on the issue in case I'm needed though. The "fun" of revocation...

**Comment by ianco** [comment] 2021-11-25 22:46
I tried updating the alice/faber demo to force alice to create proofs with timestamps even when faber doesn't ask for them (no non-revocation proof requested), and the result is an indy-sdk error when alice is trying to create the proof:

```
Alice      | 2021-11-25 22:42:55,690 aries_cloudagent.admin.server ERROR Handler error with exception: Error when constructing proof: Error: Invalid structure. Caused by: RevocationState not found by id: RevocationRegistryId("KPZxxu8tmF174CtH5bQRo5:4:KPZxxu8tmF174CtH5bQRo5:3:CL:8:faber.agent.degree_schema:CL_ACCUM:1e09ec60-362c-43f4-9c6a-97081280e203"). CommonInvalidStructure.
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/indy/sdk/holder.py", line 444, in create_presentation
Alice      |     json.dumps(rev_states) if rev_states else "{}",
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/anoncreds.py", line 1617, in prover_create_proof
Alice      |     prover_create_proof.cb)
Alice      | indy.error.CommonInvalidStructure
```

I'm going to need to see an example of this happening in real life, I can't force it using aca-py, the validation is just TOO SOLID.

**Comment by swcurran** [comment] 2022-01-11 19:50
Closing this -- I don't think there is any more to do. Please reopen if I'm misunderstanding.

**Closed as completed by swcurran** 2022-01-11 19:50 UTC
