### ISSUE TITLE
.NET image fails to build

### ISSUE THREAD

**Issue by TimoGlastra** [ianco/aries-agent-test-harness#437] opened 2022-02-16 12:25 UTC
All runsets with .NET are failing due to a build error. Not sure what caused it (I don't think it's related to changes I, or someone else, made)

error:

```
 Determining projects to restore...
  All projects are up-to-date for restore.
  Hyperledger.Aries -> /aries-framework-dotnet/src/Hyperledger.Aries/bin/Release/netstandard2.0/Hyperledger.Aries.dll
  Hyperledger.Aries.AspNetCore.Contracts -> /aries-framework-dotnet/src/Hyperledger.Aries.AspNetCore.Contracts/bin/Release/netstandard2.1/Hyperledger.Aries.AspNetCore.Contracts.dll
  Hyperledger.Aries.AspNetCore -> /aries-framework-dotnet/src/Hyperledger.Aries.AspNetCore/bin/Release/netcoreapp3.1/Hyperledger.Aries.AspNetCore.dll
Controllers/ConnectionController.cs(8,32): error CS0234: The type or namespace name 'Events' does not exist in the namespace 'Hyperledger.Aries.Models' (are you missing an assembly reference?) [/src/DotNet.Backchannel.Master.csproj]
Controllers/IssueCredentialController.cs(13,32): error CS0234: The type or namespace name 'Events' does not exist in the namespace 'Hyperledger.Aries.Models' (are you missing an assembly reference?) [/src/DotNet.Backchannel.Master.csproj]
Controllers/PresentProofController.cs(13,32): error CS0234: The type or namespace name 'Events' does not exist in the namespace 'Hyperledger.Aries.Models' (are you missing an assembly reference?) [/src/DotNet.Backchannel.Master.csproj]
Handlers/CredentialHandler.cs(18,32): error CS0234: The type or namespace name 'Events' does not exist in the namespace 'Hyperledger.Aries.Models' (are you missing an assembly reference?) [/src/DotNet.Backchannel.Master.csproj]
Controllers/ConnectionController.cs(188,122): error CS0246: The type or namespace name 'ServiceMessageProcessingEvent' could not be found (are you missing a using directive or an assembly reference?) [/src/DotNet.Backchannel.Master.csproj]
Controllers/IssueCredentialController.cs(309,155): error CS0246: The type or namespace name 'ServiceMessageProcessingEvent' could not be found (are you missing a using directive or an assembly reference?) [/src/DotNet.Backchannel.Master.csproj]
Controllers/PresentProofController.cs(200,152): error CS0246: The type or namespace name 'ServiceMessageProcessingEvent' could not be found (are you missing a using directive or an assembly reference?) [/src/DotNet.Backchannel.Master.csproj]
The command '/bin/sh -c dotnet publish "DotNet.Backchannel.Master.csproj" -c Release -o /app/publish' returned a non-zero code: 1
Docker image build failed.
```

**Comment by swcurran** [comment] 2022-02-16 15:48
Thanks, Timo -- I was going to be digging into this a bit today to see why those tests are failing.

Now to figuring out the build failure...

**Comment by swcurran** [comment] 2022-02-16 17:32
The PR merged two days ago created this issue -- the Events Model was removed from the src/Hyperledger.Aries.TestHarness/AgentScenarios.cs file -- this can be seen here: https://github.com/hyperledger/aries-framework-dotnet/pull/213/files#, the removal of line 16 from the file.

I will open a PR about this in the .NET repo.  I'm guessing that just adding the line back in might fix the issue, but I don't know how to go about testing that theory.

**Comment by swcurran** [comment] 2022-02-16 17:42
Issue has been submitted: https://github.com/hyperledger/aries-framework-dotnet/issues/215

For a temporary measure, we could reference the pre-merge commit in the AATH dockerfile until the issue is fixed.

**Closed as completed** 2022-07-07 15:53 UTC
